Repository apollographql/apollo-kotlin, pull requests merged in 2018-07, with the labels that each got.

#986 Feature/985 update index
  .gitignore
  docs/_config.yml
  docs/package.json
  docs/source/essentials/get-started.md
  docs/source/images/directory_structure.png
  docs/source/images/generated_feed_query_class_structure.png
Labels: docs

#1004 Fix race in subscription manager AutoReleaseTimer
  apollo-runtime/src/main/java/com/apollographql/apollo/internal/subscription/RealSubscriptionManager.java
Labels: blocking

#979 Deffer accessing to apollo extension properties until task execution
  .travis.yml
  README.md
  apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/GraphQLCompiler.kt
  apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/NullableValueType.kt
  apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloClassGenerationTask.groovy
  apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloExtension.groovy
  apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloLocalCodegenGenerationTask.groovy
  apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloPlugin.groovy
  apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloSystemCodegenGenerationTask.groovy
  apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/ApolloClassGenerationTask.java
  apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/ApolloExtension.java
  apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/ApolloLocalCodegenGenerationTask.java
  apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/ApolloSystemCodegenGenerationTask.java
  apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/CodegenGenerationTaskCommandArgsBuilder.java
  apollo-gradle-plugin/src/test/groovy/com/apollographql/apollo/gradle/integration/BasicAndroidSpec.groovy
  apollo-gradle-plugin/src/test/groovy/com/apollographql/apollo/gradle/integration/FlavoredMultiSchemaSpec.groovy
  apollo-gradle-plugin/src/test/groovy/com/apollographql/apollo/gradle/unit/ApolloCodeGenInstallTaskSpec.groovy
  apollo-gradle-plugin/src/test/testProject/android/buildScriptFixtures/flavored.gradle
  apollo-gradle-plugin/src/test/testProject/android/buildScriptFixtures/libraryProject.gradle
  apollo-integration/build.gradle
  gradle/composite/apollo-integration-build.gradle
Labels: Status: Review Needed
