Repository apollographql/apollo-kotlin, pull requests merged in 2021-11, with the labels that each got.

#3482 Add a "compat" v2 CustomTypeAdapter to v3 Adapter API
  apollo-api/api/apollo-api.api
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/Adapter.kt
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/ApolloInternal.kt
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/CustomScalarAdapters.kt
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/Version2CustomTypeAdapter.kt
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/internal/Version2CustomTypeAdapterToAdapter.kt
  apollo-runtime/api/apollo-runtime.api
  apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/ApolloClient.kt
  tests/integration-tests/build.gradle.kts
  tests/integration-tests/src/commonMain/kotlin/com/example/MyDate.kt
  tests/integration-tests/src/commonTest/kotlin/test/ScalarAdapterTest.kt
  tests/integration-tests/src/main/graphql/com/apollographql/apollo3/integration/fullstack/LaunchDetailsByDate.graphql
  tests/integration-tests/src/main/graphql/com/apollographql/apollo3/integration/fullstack/schema.graphqls
  tests/integration-tests/testFixtures/resources/LaunchDetailsByDateResponse.json
Labels: Component: Runtime, size/medium, 2021-11

#3500 Re generate Rx3 support from Rx2
  apollo-rx3-support/api/apollo-rx3-support.api
  apollo-rx3-support/src/main/java/com/apollographql/apollo3/rx3/toRx3.kt
  scripts/rxjava3.main.kts
Labels: size/small, 2021-11

#3506 Use 3.0.0-beta03 and its fluent API
  docs/source/tutorial/01-configure-project.mdx
  docs/source/tutorial/04-execute-the-query.mdx
  docs/source/tutorial/05-connect-queries-to-your-ui.mdx
  docs/source/tutorial/07-paginate-results.mdx
  docs/source/tutorial/08-add-a-details-view.mdx
  docs/source/tutorial/09-write-your-first-mutation.mdx
  docs/source/tutorial/10-authenticate-your-queries.mdx
  docs/source/tutorial/11-subscriptions.mdx
Labels: Type: Documentation, size/small, 2021-11

#3505 Update cache docs
  apollo-normalized-cache-api/api/apollo-normalized-cache-api.api
  apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/CacheKey.kt
  apollo-normalized-cache-common/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/MemoryCache.kt
  docs/gatsby-config.js
  docs/source/caching/declarative-ids.mdx
  docs/source/caching/http-cache.mdx
  docs/source/caching/normalized-cache.mdx
  docs/source/caching/programmatic-ids.mdx
  docs/source/caching/query-watchers.mdx
  docs/source/caching/store.mdx
  docs/source/caching/troubleshooting.mdx
Labels: size/medium, 2021-11

#3502 Add doc about Java/RxJava support
  apollo-api/api/apollo-api.api
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/ApolloExperimental.kt
  apollo-normalized-cache-common/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/internal/RxApolloStore.kt
  apollo-rx2-support/api/apollo-rx2-support.api
  apollo-rx2-support/src/main/java/com/apollographql/apollo3/rx2/toCoroutines.kt
  apollo-rx2-support/src/main/java/com/apollographql/apollo3/rx2/toRx2.kt
  apollo-rx3-support/api/apollo-rx3-support.api
  apollo-rx3-support/src/main/java/com/apollographql/apollo3/rx3/toCoroutines.kt
  apollo-rx3-support/src/main/java/com/apollographql/apollo3/rx3/toRx3.kt
  build.gradle.kts
  docs/gatsby-config.js
  docs/source/advanced/java.mdx
  docs/source/advanced/rxjava.mdx
Labels: Type: Documentation

#3543 Add documentation for apollo-ast
  docs/gatsby-config.js
  docs/source/advanced/apollo-ast.mdx
Labels: Type: Documentation, size/medium, 2021-11

#3547 Update apollo-ast doc after improving the transform API
  docs/source/advanced/apollo-ast.mdx
Labels: Type: Documentation, size/small, 2021-11

#3533 Add doc for test builders
  docs/gatsby-config.js
  docs/source/advanced/rxjava.mdx
  docs/source/advanced/test-builders.mdx
Labels: Type: Documentation, size/small, 2021-11

#3553 Add a doc for Query Batching
  apollo-runtime/api/apollo-runtime.api
  apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/http/BatchingHttpEngine.kt
  docs/gatsby-config.js
  docs/source/advanced/query-batching.mdx
  tests/integration-tests/src/commonTest/kotlin/test/batching/QueryBatchingTest.kt
Labels: Type: Documentation, size/small, 2021-11

#3557 Rename httpHeader() to addHttpHeader()
  apollo-api/api/apollo-api.api
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/ApolloRequest.kt
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/http/HttpContext.kt
  apollo-http-cache/src/main/kotlin/com/apollographql/apollo3/cache/http/HttpCacheExtensions.kt
  apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/ApolloCall.kt
  apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/ApolloClient.kt
  apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/http/BatchingHttpEngine.kt
  design-docs/Builders.md
  tests/integration-tests/src/commonTest/kotlin/test/HttpRequestComposerTest.kt
Labels: size/small, 2021-11

#3576 Improve java usability
  CONTRIBUTING.md
  apollo-api/api/apollo-api.api
  apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/CompiledGraphQL.kt
  apollo-http-cache/api/apollo-http-cache.api
  apollo-http-cache/src/main/kotlin/com/apollographql/apollo3/cache/http/HttpCacheExtensions.kt
  apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/CacheKeyGenerator.kt
  apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/CacheKeyResolver.kt
  apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/CacheResolver.kt
  apollo-normalized-cache/api/apollo-normalized-cache.api
  apollo-normalized-cache/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/ClientCacheExtensions.kt
  apollo-runtime/api/apollo-runtime.api
  apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/ApolloClient.kt
  apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/http/BatchingHttpEngine.kt
  apollo-runtime/src/jvmMain/kotlin/com/apollographql/apollo3/network/http/OkHttpEngine.kt
  apollo-rx2-support/api/apollo-rx2-support.api
  apollo-rx2-support/src/main/java/com/apollographql/apollo3/rx2/toRx2.kt
  apollo-rx3-support/api/apollo-rx3-support.api
  apollo-rx3-support/build.gradle.kts
  apollo-rx3-support/src/main/java/com/apollographql/apollo3/rx3/toRx3.kt
  docs/source/advanced/client-awareness.mdx
  tests/integration-tests/src/commonTest/kotlin/test/AutoPersistedQueriesTest.kt
  tests/integration-tests/src/commonTest/kotlin/test/declarativecache/DeclarativeCacheTest.kt
  tests/java-tests/README.md
  tests/java-tests/build.gradle.kts
  tests/java-tests/src/main/graphql/operations.graphql
  tests/java-tests/src/main/graphql/schema.graphqls
  tests/java-tests/src/test/java/test/ClientTest.java
  tests/jpms/src/main/java/com/example/app/Main.java
Labels: Type: Enhancement, size/small, Java, 2021-11
