Repository apollographql/apollo-kotlin, pull requests merged in 2021-12, with the labels that each got.

#3673 Update batching docs following api improvements
  docs/source/advanced/query-batching.mdx
Labels: Type: Documentation

#3734 [DNM] Notice for 3.0 GA
  docs/source/index.md
Labels: :hand: Blocked

#3738 Add a design doc about operation execution
  design-docs/Operation execution.md
  design-docs/assets/Operation execution diagram.drawio
  design-docs/assets/Operation execution diagram.svg
Labels: :book: Type: Documentation

#3752 Fix downloadApolloSchema task
  apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo3/gradle/internal/ApolloDownloadSchemaTask.kt
  docs/source/tutorial/02-add-the-graphql-schema.mdx
Labels: :book: Type: Documentation
